#!/bin/sh
#
#  $HEX_ROOT/pipes/grasp: 
#
#  Invoked by Hex to write a PDB-format version of the current scene into 
#  Grasp. NB. Hex arranges that its output appears on stdin for this script 
#  so that "cat" can read it.
#
#  Dave Ritchie, November 2000
#

pid=$$

tmp_pdb=/tmp/hex_grasp_${pid}.pdb

cat > $tmp_pdb

grasp $tmp_pdb 

rm -f $tmp_pdb
