#!/bin/sh
#
#  $HEX_ROOT/pipes/molscript: 
#
#  Invoked by Hex to write a PDB-format version of the current scene into 
#  molscript and to view the output with ghostview. NB. Hex arranges that
#  its output appears on stdin for this script so that "cat" can read it.
#
#  Neither Molauto nor Ghostview read stdin - scratch files to the rescue!
#
#  Dave Ritchie, October 2000
#

pid=$$

tmp_pdb=/tmp/hex_molscript_${pid}.pdb
tmp_ps=/tmp/hex_molscript_${pid}.ps

cat > $tmp_pdb

molauto $tmp_pdb | molscript > $tmp_ps

gv $tmp_ps

rm -f $tmp_pdb $tmp_ps
