#
#  make_wcc.mac    - creates $HEX_ROOT/data/wigner_coeffs.dat
#
#
#  This macro can only be executed on machines with 16-byte quad-precision 
#  arithmetic (i.e. most Unix workstations: e.g. SGI, SUN, etc.). It causes 
#  Hex to write out a list of Wigner coupling coefficients (multiplied 
#  by a square root or two) to the file "$HEX_ROOT/data/wigner_coeffs.dat".
#  These coefficients are used when calculating translation matrix elements 
#  in Hex's docking calculations.
#
#  The resulting file of coefficients is only *required* on machines with
#  12-byte long doubles (such as the Intel/Pentium) since the necessary 
#  coefficients cannot be calculated sufficiently accurately at run-time.
#  On other machines the coefficient file is used, if found, since its
#  normally faster to read from the file than it is to calculate afresh
#  every time (about 30 seconds to N=30).
#
#  This file is here for reference only, because comments aren't allowed 
#  in the actual coefficient file.

MAKE_WCC 30
