---
os: linux
dist: focal
language: python
services: 
  - mysql
  - redis
python: 
  - 3.7
  - 3.8
  - 3.9-dev
  # - nightly # Numpy
  # - pypy3 # Pandas
before_install: 
  - bash ./config/init.sh
install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
script: 
  - flake8
  # Test with no cache
  - pytest -s
  # Test with cache: Results should be same
  - pytest -s
  - redis-cli flushall
  - coverage run
  - coverage report
after_success:
  - coveralls

