services:

  mysqldb:
    image: mysql:9.4.0
    container_name: BAR_mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:8.0.3
    container_name: BAR_redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: BAR_API
    command: wait-for-it --strict BAR_mysqldb:3306 -- ./config/init.sh
    restart: always
    # Run like it's running on CI/CD pipeline
    environment:
      - REDIS_HOST=BAR_redis
      - REDIS_PORT=6379
      - CI=TRUE
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mysqldb
    volumes:
      - './api:/usr/src/app/api'
      - './tests:/usr/src/app/tests'

