#
#  3hfl_fv.mac
#  ===========
#
#  This example macro file loads the HyHel-5/lysozyme antibody/antigen 
#  complex. By default, Hex will look in the $HEX_ROOT/examples directory
#  for the pdb files and the colour file referenced here. You may wish to
#  change this behaviour by setting some environment variables in your
#  .login (csh) or .profile (sh/ksh) files.
#

CLOSE_ALL

SET_COLOUR_FILE 3hfl.col

OPEN_RECEPTOR   3hfl_fv.pdb
# OPEN_RECEPTOR   3hfl_fab.pdb
OPEN_LIGAND     3hfl_ly.pdb
OPEN_COMPLEX    3hfl.pdb

FIT_LIGAND

# RECEPTOR_ORIGIN H-36

