#
#  dock_2ptc.mac - constrained docking (v. quick check with bound subunits)
#

DOCKING_RECEPTOR_SAMPLES  492
DOCKING_LIGAND_SAMPLES    492
DOCKING_ALPHA_SAMPLES     128

RECEPTOR_RANGE_ANGLE       30
LIGAND_RANGE_ANGLE         30
TWIST_RANGE_ANGLE         360

R12_RANGE                  21
R12_STEP                 0.75
GRID_SIZE                0.6
LIGAND_RANGE_ANGLE         30
RECEPTOR_RANGE_ANGLE       30

DOCKING_MAIN_SCAN          16
DOCKING_MAIN_SEARCH        25

RUN_MACRO 2ptc.mac

ACTIVATE_DOCKING

