#
#  dock_3hfl_short.mac - local docking to test recognition of bound subunits
#

DOCKING_RECEPTOR_SAMPLES  492
DOCKING_LIGAND_SAMPLES    492
DOCKING_ALPHA_SAMPLES     128

LIGAND_RANGE_ANGLE         45
RECEPTOR_RANGE_ANGLE       45
TWIST_RANGE_ANGLE         360

R12_RANGE                  15
R12_STEP                 0.75
GRID_SIZE                0.6

DOCKING_MAIN_SCAN          16
DOCKING_MAIN_SEARCH        25

RUN_MACRO 3hfl_fv.mac

ACTIVATE_DOCKING

