#
#  dock_ptc.mac: predictive docking, randomised ligand, known receptor epitope
#
DOCKING_RECEPTOR_SAMPLES  492
DOCKING_LIGAND_SAMPLES    492
DOCKING_ALPHA_SAMPLES     128

RECEPTOR_RANGE_ANGLE      180
LIGAND_RANGE_ANGLE         30
TWIST_RANGE_ANGLE         360

R12_RANGE                  21
R12_STEP                 0.75
GRID_SIZE                0.6

DOCKING_MAIN_SCAN          16
DOCKING_MAIN_SEARCH        25

RUN_MACRO ptc.mac

RUN_MACRO randomise_ligand.mac

ACTIVATE_DOCKING

