#
#  dock_hfl.mac - docking using unbound subunits, constrained to epitopes
#
DOCKING_RECEPTOR_SAMPLES  492
DOCKING_LIGAND_SAMPLES    492
DOCKING_ALPHA_SAMPLES     128

RECEPTOR_RANGE_ANGLE       30
LIGAND_RANGE_ANGLE         30
TWIST_RANGE_ANGLE         360

R12_RANGE                  31
R12_STEP                 0.75
GRID_SIZE                0.6
LIGAND_RANGE_ANGLE         30
RECEPTOR_RANGE_ANGLE       30

RUN_MACRO hfl.mac

RUN_MACRO randomise_ligand.mac

ACTIVATE_DOCKING

