#
#  match_ptc.mac: example superposition of two similar protein domains
#

open_receptor              2ptc_e.pdb 
open_ligand                2ptn_e.pdb

max_matching_solutions     10

matching_grid_size         0.6

receptor_range_angle       180
ligand_range_angle         180

matching_receptor_stepsize 20.0
matching_ligand_stepsize   20.0
matching_alpha_stepsize     5.5

matching_r12_range          10
matching_r12_step            0.8

matching_main_search         6

activate_matching
