-- MySQL Script generated by MySQL Workbench
-- Tue Apr 12 12:02:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `tomato_sequence` DEFAULT CHARACTER SET utf8 ;

USE `tomato_sequence` ;

-- -----------------------------------------------------
-- Table ``.`tomato_3_2_sequence_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tomato_3_2_sequence_info` ;

CREATE TABLE IF NOT EXISTS `tomato_3_2_sequence_info` (
  `gene_id` VARCHAR(20) NOT NULL,
  `full_seq` VARCHAR(9999) NULL,
  `full_seq_len` INT NULL,
  `phyre2_seq` VARCHAR(9999) NULL,
  `phyre2_seq_start` INT NULL,
  `phyre2_seq_end` INT NULL,
  PRIMARY KEY (`gene_id`))
ENGINE=InnoDB DEFAULT CHARSET=latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `tomato_3_2_sequence_info`
-- -----------------------------------------------------
START TRANSACTION;
USE `tomato_sequence`;
INSERT INTO `tomato_3_2_sequence_info` (`gene_id`, `full_seq`, `full_seq_len`, `phyre2_seq`, `phyre2_seq_start`, `phyre2_seq_end`) VALUES ('Solyc00g005445.1.1', 'MSIFSDKIEDTIEQPTDESRSLMLADNVYIHVLSAYKLWRKYSSKKQTRKIFLLIRKEVHKQIGCQYTGVTLSEWQLEYAKLRVERADLQVVLSFIVLFIATRKDLEEATKVVQEKMIVCRIEACRGVWTKVQEGALESSVI*', 143, 'KEVHKQIGCQYTGVTLSEWQLEYAKLRVERADLQVVLSFIVLFIATRKDLEEATKVVQEKMIVCRIEA', 57, 124);

COMMIT;

