"""
Compact schema definitions for eFP databases exposing a sample_data table.

Each database only needs 3 columns: data_probeset_id, data_signal, data_bot_id.
All databases share the same column structure (VARCHAR(255) for string columns).
"""

from __future__ import annotations

from typing import Any, Dict, List

ColumnSpec = Dict[str, Any]
DatabaseSpec = Dict[str, Any]

_SCHEMA_TEMPLATE: DatabaseSpec = {
    "table_name": "sample_data",
    "columns": [
        {"name": "data_probeset_id", "type": "string", "length": 255, "nullable": True, "primary_key": True},
        {"name": "data_signal", "type": "float", "nullable": True, "primary_key": True},
        {"name": "data_bot_id", "type": "string", "length": 255, "nullable": True, "primary_key": True},
    ],
    "index": ["data_probeset_id", "data_bot_id", "data_signal"],
    "identifier_type": "agi",
}


def _schema(species: str, charset: str = "latin1") -> DatabaseSpec:
    """Build a schema for one eFP database.

    :param species: Species name for metadata.
    :param charset: MySQL character set ('latin1' or 'utf8mb4').
    :return: Full database schema specification.
    """
    return {
        **_SCHEMA_TEMPLATE,
        "charset": charset,
        "metadata": {"species": species, "sample_regex": r"^[\w.\-]+$"},
    }


# fmt: off
# (name, species)
_SPECS: List[tuple] = [
    ("actinidia_bud_development", "actinidia"),
    ("actinidia_flower_fruit_development", "actinidia"),
    ("actinidia_postharvest", "actinidia"),
    ("actinidia_vegetative_growth", "actinidia"),
    ("affydb", "arabidopsis"),
    ("apple", "apple"),
    ("arabidopsis_ecotypes", "arabidopsis"),
    ("arachis", "arachis"),
    ("atgenexp", "arabidopsis"),
    ("atgenexp_hormone", "arabidopsis"),
    ("atgenexp_pathogen", "arabidopsis"),
    ("atgenexp_plus", "arabidopsis"),
    ("atgenexp_stress", "arabidopsis"),
    ("barley_mas", "barley"),
    ("barley_rma", "barley"),
    ("barley_seed", "barley"),
    ("barley_spike_meristem", "barley"),
    ("barley_spike_meristem_v3", "barley"),
    ("brachypodium", "brachypodium"),
    ("brachypodium_Bd21", "brachypodium"),
    ("brachypodium_embryogenesis", "brachypodium"),
    ("brachypodium_grains", "brachypodium"),
    ("brachypodium_metabolites_map", "brachypodium"),
    ("brachypodium_photo_thermocycle", "brachypodium"),
    ("brassica_rapa", "brassica"),
    ("cacao_developmental_atlas", "cacao"),
    ("cacao_developmental_atlas_sca", "cacao"),
    ("cacao_drought_diurnal_atlas", "cacao"),
    ("cacao_drought_diurnal_atlas_sca", "cacao"),
    ("cacao_infection", "cacao"),
    ("cacao_leaf", "cacao"),
    ("cacao_meristem_atlas_sca", "cacao"),
    ("cacao_seed_atlas_sca", "cacao"),
    ("camelina", "camelina"),
    ("camelina_tpm", "camelina"),
    ("cannabis", "cannabis"),
    ("canola", "canola"),
    ("canola_original", "canola"),
    ("canola_original_v2", "canola"),
    ("canola_seed", "canola"),
    ("cassava_atlas", "cassava"),
    ("cassava_cbb", "cassava"),
    ("cassava_eacmv", "cassava"),
    ("circadian_mutants", "circadian mutants"),
    ("cuscuta", "cuscuta"),
    ("cuscuta_early_haustoriogenesis", "cuscuta"),
    ("cuscuta_lmd", "cuscuta"),
    ("dna_damage", "arabidopsis"),
    ("durum_wheat_abiotic_stress", "wheat"),
    ("durum_wheat_biotic_stress", "wheat"),
    ("durum_wheat_development", "wheat"),
    ("embryo", "arabidopsis"),
    ("eucalyptus", "eucalyptus"),
    ("euphorbia", "euphorbia"),
    ("gc_drought", "gc drought"),
    ("germination", "arabidopsis"),
    ("grape_developmental", "grape"),
    ("guard_cell", "guard cell"),
    ("gynoecium", "gynoecium"),
    ("heterodera_schachtii", "heterodera"),
    ("hnahal", "hnahal"),
    ("human_body_map_2", "human"),
    ("human_developmental", "human"),
    ("human_developmental_SpongeLab", "human"),
    ("human_diseased", "human"),
    ("kalanchoe", "kalanchoe"),
    ("kalanchoe_time_course_analysis", "kalanchoe"),
    ("klepikova", "arabidopsis"),
    ("lateral_root_initiation", "arabidopsis"),
    ("light_series", "light series"),
    ("lipid_map", "lipid map"),
    ("little_millet", "little_millet"),
    ("lupin_lcm_leaf", "lupin"),
    ("lupin_lcm_pod", "lupin"),
    ("lupin_lcm_stem", "lupin"),
    ("lupin_pod_seed", "lupin"),
    ("lupin_whole_plant", "lupin"),
    ("maize_RMA_linear", "maize"),
    ("maize_RMA_log", "maize"),
    ("maize_atlas", "maize"),
    ("maize_atlas_v5", "maize"),
    ("maize_buell_lab", "maize"),
    ("maize_early_seed", "maize"),
    ("maize_ears", "maize"),
    ("maize_embryonic_leaf_development", "maize"),
    ("maize_enzyme", "maize"),
    ("maize_gdowns", "maize"),
    ("maize_iplant", "maize"),
    ("maize_kernel_v5", "maize"),
    ("maize_leaf_gradient", "maize"),
    ("maize_lipid_map", "maize"),
    ("maize_metabolite", "maize"),
    ("maize_nitrogen_use_efficiency", "maize"),
    ("maize_rice_comparison", "maize"),
    ("maize_root", "maize"),
    ("maize_stress_v5", "maize"),
    ("mangosteen_aril_vs_rind", "mangosteen"),
    ("mangosteen_callus", "mangosteen"),
    ("mangosteen_diseased_vs_normal", "mangosteen"),
    ("mangosteen_fruit_ripening", "mangosteen"),
    ("mangosteen_seed_development", "mangosteen"),
    ("mangosteen_seed_development_germination", "mangosteen"),
    ("mangosteen_seed_germination", "mangosteen"),
    ("marchantia_organ_stress", "marchantia"),
    ("medicago_mas", "medicago"),
    ("medicago_rma", "medicago"),
    ("medicago_root", "medicago"),
    ("medicago_root_v5", "medicago"),
    ("medicago_seed", "medicago"),
    ("meristem_db", "meristem db"),
    ("meristem_db_new", "meristem db new"),
    ("mouse_db", "mouse"),
    ("oat", "oat"),
    ("phelipanche", "phelipanche"),
    ("physcomitrella_db", "physcomitrella"),
    ("poplar", "poplar"),
    ("poplar_hormone", "poplar"),
    ("poplar_leaf", "poplar"),
    ("poplar_xylem", "poplar"),
    ("potato_dev", "potato"),
    ("potato_stress", "potato"),
    ("potato_wounding", "potato"),
    ("rice_abiotic_stress_sc_pseudobulk", "rice"),
    ("rice_drought_heat_stress", "rice"),
    ("rice_leaf_gradient", "rice"),
    ("rice_maize_comparison", "maize"),
    ("rice_mas", "rice"),
    ("rice_metabolite", "rice"),
    ("rice_rma", "rice"),
    ("rice_root", "rice"),
    ("rohan", "rohan"),
    ("root", "root"),
    ("root_Schaefer_lab", "root Schaefer lab"),
    ("rpatel", "rpatel"),
    ("seed_db", "seed db"),
    ("seedcoat", "oat"),
    ("selaginella", "selaginella"),
    ("shoot_apex", "arabidopsis"),
    ("silique", "arabidopsis"),
    ("single_cell", "arabidopsis"),
    ("sorghum_atlas_w_BS_cells", "sorghum"),
    ("sorghum_comparative_transcriptomics", "sorghum"),
    ("sorghum_developmental", "sorghum"),
    ("sorghum_developmental_2", "sorghum"),
    ("sorghum_flowering_activation", "sorghum"),
    ("sorghum_low_phosphorus", "sorghum"),
    ("sorghum_nitrogen_stress", "sorghum"),
    ("sorghum_nitrogen_use_efficiency", "sorghum"),
    ("sorghum_phosphate_stress", "sorghum"),
    ("sorghum_plasma", "sorghum"),
    ("sorghum_saline_alkali_stress", "sorghum"),
    ("sorghum_stress", "sorghum"),
    ("sorghum_strigolactone_variation", "sorghum"),
    ("sorghum_sulfur_stress", "sorghum"),
    ("sorghum_temperature_stress", "sorghum"),
    ("sorghum_vascularization_and_internode", "sorghum"),
    ("soybean", "soybean"),
    ("soybean_embryonic_development", "soybean"),
    ("soybean_heart_cotyledon_globular", "soybean"),
    ("soybean_senescence", "soybean"),
    ("soybean_severin", "soybean"),
    ("spruce", "spruce"),
    ("strawberry", "strawberry"),
    ("striga", "striga"),
    ("sugarcane_culms", "sugarcane"),
    ("sugarcane_leaf", "sugarcane"),
    ("sunflower", "sunflower"),
    ("thellungiella_db", "thellungiella"),
    ("tomato", "tomato"),
    ("tomato_ils", "tomato"),
    ("tomato_ils2", "tomato"),
    ("tomato_ils3", "tomato"),
    ("tomato_meristem", "tomato"),
    ("tomato_renormalized", "tomato"),
    ("tomato_root", "tomato"),
    ("tomato_root_field_pot", "tomato"),
    ("tomato_s_pennellii", "tomato"),
    ("tomato_seed", "tomato"),
    ("tomato_shade_mutants", "tomato"),
    ("tomato_shade_timecourse", "tomato"),
    ("tomato_trait", "tomato"),
    ("triphysaria", "triphysaria"),
    ("triticale", "triticale"),
    ("triticale_mas", "triticale"),
    ("tung_tree", "tung_tree"),
    ("wheat", "wheat"),
    ("wheat_abiotic_stress", "wheat"),
    ("wheat_embryogenesis", "wheat"),
    ("wheat_meiosis", "wheat"),
    ("wheat_root", "wheat"),
    ("willow", "willow"),
]

# databases that store Affymetrix/microarray probeset IDs instead of gene identifiers.
# For Arabidopsis databases in this set, the API will auto-convert AGI → probeset
# via the at_agi_lookup service before querying expression data.
_PROBESET_DBS = {
    # Arabidopsis microarray databases (Affymetrix ATH1 chip, need AGI→probeset lookup)
    "affydb",
    "arabidopsis_ecotypes",
    "atgenexp",
    "atgenexp_hormone",
    "atgenexp_pathogen",
    "atgenexp_plus",
    "atgenexp_stress",
    "guard_cell",
    "hnahal",
    "lateral_root_initiation",
    "light_series",
    "meristem_db",
    "meristem_db_new",
    "root",
    "rohan",
    "rpatel",
    "seed_db",
    # Non-Arabidopsis microarray databases (probeset IDs, no AGI lookup needed)
    "barley_mas",
    "barley_rma",
    "human_developmental",
    "human_developmental_SpongeLab",
    "human_diseased",
    "maize_gdowns",
    "medicago_mas",
    "medicago_rma",
    "poplar",
    "rice_mas",
    "rice_rma",
    "triticale",
    "triticale_mas",
}

# databases that use utf8mb4 charset (all others default to latin1)
_UTF8MB4 = {
    "actinidia_bud_development", "actinidia_flower_fruit_development",
    "actinidia_postharvest", "actinidia_vegetative_growth", "apple",
    "barley_seed", "barley_spike_meristem_v3",
    "brachypodium_Bd21", "brachypodium_grains", "brachypodium_metabolites_map",
    "brassica_rapa",
    "cacao_developmental_atlas", "cacao_developmental_atlas_sca",
    "cacao_drought_diurnal_atlas", "cacao_drought_diurnal_atlas_sca",
    "cacao_infection", "cacao_leaf", "cacao_meristem_atlas_sca", "cacao_seed_atlas_sca",
    "canola_seed",
    "cassava_atlas", "cassava_cbb", "cassava_eacmv",
    "circadian_mutants", "cuscuta", "cuscuta_early_haustoriogenesis", "cuscuta_lmd",
    "dna_damage",
    "durum_wheat_abiotic_stress", "durum_wheat_biotic_stress", "durum_wheat_development",
    "eucalyptus", "euphorbia",
    "gc_drought", "gynoecium", "heterodera_schachtii",
    "kalanchoe_time_course_analysis",
    "lateral_root_initiation", "lipid_map", "little_millet",
    "lupin_lcm_leaf", "lupin_lcm_pod", "lupin_lcm_stem", "lupin_pod_seed", "lupin_whole_plant",
    "maize_atlas_v5", "maize_embryonic_leaf_development", "maize_kernel_v5",
    "maize_lipid_map", "maize_nitrogen_use_efficiency", "maize_stress_v5",
    "mangosteen_aril_vs_rind", "mangosteen_callus", "mangosteen_diseased_vs_normal",
    "mangosteen_fruit_ripening", "mangosteen_seed_development",
    "mangosteen_seed_development_germination", "mangosteen_seed_germination",
    "marchantia_organ_stress",
    "medicago_root", "medicago_root_v5",
    "oat", "phelipanche", "poplar_hormone", "potato_wounding",
    "rice_abiotic_stress_sc_pseudobulk", "rice_drought_heat_stress", "rice_root",
    "silique",
    "sorghum_atlas_w_BS_cells", "sorghum_comparative_transcriptomics",
    "sorghum_developmental", "sorghum_developmental_2", "sorghum_flowering_activation",
    "sorghum_low_phosphorus", "sorghum_nitrogen_stress", "sorghum_nitrogen_use_efficiency",
    "sorghum_phosphate_stress", "sorghum_plasma", "sorghum_saline_alkali_stress",
    "sorghum_stress", "sorghum_strigolactone_variation", "sorghum_sulfur_stress",
    "sorghum_temperature_stress", "sorghum_vascularization_and_internode",
    "soybean_embryonic_development", "soybean_heart_cotyledon_globular", "soybean_senescence",
    "spruce", "strawberry",
    "sugarcane_culms", "sugarcane_leaf",
    "tomato_root", "tomato_root_field_pot", "tomato_seed",
    "tomato_shade_mutants", "tomato_shade_timecourse",
    "triphysaria",
    "wheat_abiotic_stress", "wheat_meiosis", "wheat_root",
}
# fmt: on

SIMPLE_EFP_DATABASE_SCHEMAS: Dict[str, DatabaseSpec] = {
    n: {
        **_schema(s, "utf8mb4" if n in _UTF8MB4 else "latin1"),
        **({"identifier_type": "probeset"} if n in _PROBESET_DBS else {}),
    }
    for n, s in _SPECS
}

__all__: List[str] = ["SIMPLE_EFP_DATABASE_SCHEMAS", "ColumnSpec", "DatabaseSpec"]
